# Orb 'circleci/maven@0.0.12' resolved to 'circleci/maven@0.0.12'
version: 2
jobs:
  maven/test:
    docker:
    - image: circleci/openjdk:13.0.2-jdk-buster-browsers-legacy #Docker image changed to a java 13 version
    steps:
    - checkout
    - run:
        name: Generate Cache Checksum
        command: find . -name '/microservice-musicians/pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
    - restore_cache:
        key: maven-{{ checksum "/tmp/maven_cache_seed" }}
    - run:
        name: Install Dependencies
        command: mvn dependency:go-offline --settings '/microservice-musicians/pom.xml'
    - run:
        name: Run Tests
        command: mvn verify --settings '/microservice-musicians/pom.xml'
    - save_cache:
        paths:
        - ~/.m2
        key: maven-{{ checksum "/tmp/maven_cache_seed" }}
    - store_test_results:
        path: /microservice-musicians/target/surefire-reports
workflows:
  maven_test:
    jobs:
    - maven/test
  version: 2

# Original config.yml file:
# version: 2.1
# 
# orbs:
#   maven: circleci/maven@0.0.12
# 
# workflows:
#   maven_test:
#     jobs:
#       - maven/test # checkout, build, test, and upload test results