-- countries (iso, name)
INSERT INTO countries (iso, name) VALUES ('AF', 'Afghanistan');
INSERT INTO countries (iso, name) VALUES ('AL', 'Albania');
INSERT INTO countries (iso, name) VALUES ('DZ', 'Algeria');
INSERT INTO countries (iso, name) VALUES ('DS', 'American Samoa');
INSERT INTO countries (iso, name) VALUES ('AD', 'Andorra');
INSERT INTO countries (iso, name) VALUES ('AO', 'Angola');
INSERT INTO countries (iso, name) VALUES ('AI', 'Anguilla');
INSERT INTO countries (iso, name) VALUES ('AQ', 'Antarctica');
INSERT INTO countries (iso, name) VALUES ('AG', 'Antigua and Barbuda');
INSERT INTO countries (iso, name) VALUES ('AR', 'Argentina');
INSERT INTO countries (iso, name) VALUES ('AM', 'Armenia');
INSERT INTO countries (iso, name) VALUES ('AW', 'Aruba');
INSERT INTO countries (iso, name) VALUES ('AU', 'Australia');
INSERT INTO countries (iso, name) VALUES ('AT', 'Austria');
INSERT INTO countries (iso, name) VALUES ('AZ', 'Azerbaijan');
INSERT INTO countries (iso, name) VALUES ('BS', 'Bahamas');
INSERT INTO countries (iso, name) VALUES ('BH', 'Bahrain');
INSERT INTO countries (iso, name) VALUES ('BD', 'Bangladesh');
INSERT INTO countries (iso, name) VALUES ('BB', 'Barbados');
INSERT INTO countries (iso, name) VALUES ('BY', 'Belarus');
INSERT INTO countries (iso, name) VALUES ('BE', 'Belgium');
INSERT INTO countries (iso, name) VALUES ('BZ', 'Belize');
INSERT INTO countries (iso, name) VALUES ('BJ', 'Benin');
INSERT INTO countries (iso, name) VALUES ('BM', 'Bermuda');
INSERT INTO countries (iso, name) VALUES ('BT', 'Bhutan');
INSERT INTO countries (iso, name) VALUES ('BO', 'Bolivia');
INSERT INTO countries (iso, name) VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO countries (iso, name) VALUES ('BW', 'Botswana');
INSERT INTO countries (iso, name) VALUES ('BV', 'Bouvet Island');
INSERT INTO countries (iso, name) VALUES ('BR', 'Brazil');
INSERT INTO countries (iso, name) VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO countries (iso, name) VALUES ('BN', 'Brunei Darussalam');
INSERT INTO countries (iso, name) VALUES ('BG', 'Bulgaria');
INSERT INTO countries (iso, name) VALUES ('BF', 'Burkina Faso');
INSERT INTO countries (iso, name) VALUES ('BI', 'Burundi');
INSERT INTO countries (iso, name) VALUES ('KH', 'Cambodia');
INSERT INTO countries (iso, name) VALUES ('CM', 'Cameroon');
INSERT INTO countries (iso, name) VALUES ('CA', 'Canada');
INSERT INTO countries (iso, name) VALUES ('CV', 'Cape Verde');
INSERT INTO countries (iso, name) VALUES ('KY', 'Cayman Islands');
INSERT INTO countries (iso, name) VALUES ('CF', 'Central African Republic');
INSERT INTO countries (iso, name) VALUES ('TD', 'Chad');
INSERT INTO countries (iso, name) VALUES ('CL', 'Chile');
INSERT INTO countries (iso, name) VALUES ('CN', 'China');
INSERT INTO countries (iso, name) VALUES ('CX', 'Christmas Island');
INSERT INTO countries (iso, name) VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO countries (iso, name) VALUES ('CO', 'Colombia');
INSERT INTO countries (iso, name) VALUES ('KM', 'Comoros');
INSERT INTO countries (iso, name) VALUES ('CD', 'Democratic Republic of the Congo');
INSERT INTO countries (iso, name) VALUES ('CG', 'Republic of Congo');
INSERT INTO countries (iso, name) VALUES ('CK', 'Cook Islands');
INSERT INTO countries (iso, name) VALUES ('CR', 'Costa Rica');
INSERT INTO countries (iso, name) VALUES ('HR', 'Croatia (Hrvatska)');
INSERT INTO countries (iso, name) VALUES ('CU', 'Cuba');
INSERT INTO countries (iso, name) VALUES ('CY', 'Cyprus');
INSERT INTO countries (iso, name) VALUES ('CZ', 'Czech Republic');
INSERT INTO countries (iso, name) VALUES ('DK', 'Denmark');
INSERT INTO countries (iso, name) VALUES ('DJ', 'Djibouti');
INSERT INTO countries (iso, name) VALUES ('DM', 'Dominica');
INSERT INTO countries (iso, name) VALUES ('DO', 'Dominican Republic');
INSERT INTO countries (iso, name) VALUES ('TP', 'East Timor');
INSERT INTO countries (iso, name) VALUES ('EC', 'Ecuador');
INSERT INTO countries (iso, name) VALUES ('EG', 'Egypt');
INSERT INTO countries (iso, name) VALUES ('SV', 'El Salvador');
INSERT INTO countries (iso, name) VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO countries (iso, name) VALUES ('ER', 'Eritrea');
INSERT INTO countries (iso, name) VALUES ('EE', 'Estonia');
INSERT INTO countries (iso, name) VALUES ('ET', 'Ethiopia');
INSERT INTO countries (iso, name) VALUES ('FK', 'Falkland Islands (Malvinas)');
INSERT INTO countries (iso, name) VALUES ('FO', 'Faroe Islands');
INSERT INTO countries (iso, name) VALUES ('FJ', 'Fiji');
INSERT INTO countries (iso, name) VALUES ('FI', 'Finland');
INSERT INTO countries (iso, name) VALUES ('FR', 'France');
INSERT INTO countries (iso, name) VALUES ('FX', 'France, Metropolitan');
INSERT INTO countries (iso, name) VALUES ('GF', 'French Guiana');
INSERT INTO countries (iso, name) VALUES ('PF', 'French Polynesia');
INSERT INTO countries (iso, name) VALUES ('TF', 'French Southern Territories');
INSERT INTO countries (iso, name) VALUES ('GA', 'Gabon');
INSERT INTO countries (iso, name) VALUES ('GM', 'Gambia');
INSERT INTO countries (iso, name) VALUES ('GE', 'Georgia');
INSERT INTO countries (iso, name) VALUES ('DE', 'Germany');
INSERT INTO countries (iso, name) VALUES ('GH', 'Ghana');
INSERT INTO countries (iso, name) VALUES ('GI', 'Gibraltar');
INSERT INTO countries (iso, name) VALUES ('GK', 'Guernsey');
INSERT INTO countries (iso, name) VALUES ('GR', 'Greece');
INSERT INTO countries (iso, name) VALUES ('GL', 'Greenland');
INSERT INTO countries (iso, name) VALUES ('GD', 'Grenada');
INSERT INTO countries (iso, name) VALUES ('GP', 'Guadeloupe');
INSERT INTO countries (iso, name) VALUES ('GU', 'Guam');
INSERT INTO countries (iso, name) VALUES ('GT', 'Guatemala');
INSERT INTO countries (iso, name) VALUES ('GN', 'Guinea');
INSERT INTO countries (iso, name) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO countries (iso, name) VALUES ('GY', 'Guyana');
INSERT INTO countries (iso, name) VALUES ('HT', 'Haiti');
INSERT INTO countries (iso, name) VALUES ('HM', 'Heard and Mc Donald Islands');
INSERT INTO countries (iso, name) VALUES ('HN', 'Honduras');
INSERT INTO countries (iso, name) VALUES ('HK', 'Hong Kong');
INSERT INTO countries (iso, name) VALUES ('HU', 'Hungary');
INSERT INTO countries (iso, name) VALUES ('IS', 'Iceland');
INSERT INTO countries (iso, name) VALUES ('IN', 'India');
INSERT INTO countries (iso, name) VALUES ('IM', 'Isle of Man');
INSERT INTO countries (iso, name) VALUES ('ID', 'Indonesia');
INSERT INTO countries (iso, name) VALUES ('IR', 'Iran (Islamic Republic of)');
INSERT INTO countries (iso, name) VALUES ('IQ', 'Iraq');
INSERT INTO countries (iso, name) VALUES ('IE', 'Ireland');
INSERT INTO countries (iso, name) VALUES ('IL', 'Israel');
INSERT INTO countries (iso, name) VALUES ('IT', 'Italy');
INSERT INTO countries (iso, name) VALUES ('CI', 'Ivory Coast');
INSERT INTO countries (iso, name) VALUES ('JE', 'Jersey');
INSERT INTO countries (iso, name) VALUES ('JM', 'Jamaica');
INSERT INTO countries (iso, name) VALUES ('JP', 'Japan');
INSERT INTO countries (iso, name) VALUES ('JO', 'Jordan');
INSERT INTO countries (iso, name) VALUES ('KZ', 'Kazakhstan');
INSERT INTO countries (iso, name) VALUES ('KE', 'Kenya');
INSERT INTO countries (iso, name) VALUES ('KI', 'Kiribati');
INSERT INTO countries (iso, name) VALUES ('KP', 'Korea, Democratic People''s Republic of');
INSERT INTO countries (iso, name) VALUES ('KR', 'Korea, Republic of');
INSERT INTO countries (iso, name) VALUES ('XK', 'Kosovo');
INSERT INTO countries (iso, name) VALUES ('KW', 'Kuwait');
INSERT INTO countries (iso, name) VALUES ('KG', 'Kyrgyzstan');
INSERT INTO countries (iso, name) VALUES ('LA', 'Lao People''s Democratic Republic');
INSERT INTO countries (iso, name) VALUES ('LV', 'Latvia');
INSERT INTO countries (iso, name) VALUES ('LB', 'Lebanon');
INSERT INTO countries (iso, name) VALUES ('LS', 'Lesotho');
INSERT INTO countries (iso, name) VALUES ('LR', 'Liberia');
INSERT INTO countries (iso, name) VALUES ('LY', 'Libyan Arab Jamahiriya');
INSERT INTO countries (iso, name) VALUES ('LI', 'Liechtenstein');
INSERT INTO countries (iso, name) VALUES ('LT', 'Lithuania');
INSERT INTO countries (iso, name) VALUES ('LU', 'Luxembourg');
INSERT INTO countries (iso, name) VALUES ('MO', 'Macau');
INSERT INTO countries (iso, name) VALUES ('MK', 'North Macedonia');
INSERT INTO countries (iso, name) VALUES ('MG', 'Madagascar');
INSERT INTO countries (iso, name) VALUES ('MW', 'Malawi');
INSERT INTO countries (iso, name) VALUES ('MY', 'Malaysia');
INSERT INTO countries (iso, name) VALUES ('MV', 'Maldives');
INSERT INTO countries (iso, name) VALUES ('ML', 'Mali');
INSERT INTO countries (iso, name) VALUES ('MT', 'Malta');
INSERT INTO countries (iso, name) VALUES ('MH', 'Marshall Islands');
INSERT INTO countries (iso, name) VALUES ('MQ', 'Martinique');
INSERT INTO countries (iso, name) VALUES ('MR', 'Mauritania');
INSERT INTO countries (iso, name) VALUES ('MU', 'Mauritius');
INSERT INTO countries (iso, name) VALUES ('TY', 'Mayotte');
INSERT INTO countries (iso, name) VALUES ('MX', 'Mexico');
INSERT INTO countries (iso, name) VALUES ('FM', 'Micronesia, Federated States of');
INSERT INTO countries (iso, name) VALUES ('MD', 'Moldova, Republic of');
INSERT INTO countries (iso, name) VALUES ('MC', 'Monaco');
INSERT INTO countries (iso, name) VALUES ('MN', 'Mongolia');
INSERT INTO countries (iso, name) VALUES ('ME', 'Montenegro');
INSERT INTO countries (iso, name) VALUES ('MS', 'Montserrat');
INSERT INTO countries (iso, name) VALUES ('MA', 'Morocco');
INSERT INTO countries (iso, name) VALUES ('MZ', 'Mozambique');
INSERT INTO countries (iso, name) VALUES ('MM', 'Myanmar');
INSERT INTO countries (iso, name) VALUES ('NA', 'Namibia');
INSERT INTO countries (iso, name) VALUES ('NR', 'Nauru');
INSERT INTO countries (iso, name) VALUES ('NP', 'Nepal');
INSERT INTO countries (iso, name) VALUES ('NL', 'Netherlands');
INSERT INTO countries (iso, name) VALUES ('AN', 'Netherlands Antilles');
INSERT INTO countries (iso, name) VALUES ('NC', 'New Caledonia');
INSERT INTO countries (iso, name) VALUES ('NZ', 'New Zealand');
INSERT INTO countries (iso, name) VALUES ('NI', 'Nicaragua');
INSERT INTO countries (iso, name) VALUES ('NE', 'Niger');
INSERT INTO countries (iso, name) VALUES ('NG', 'Nigeria');
INSERT INTO countries (iso, name) VALUES ('NU', 'Niue');
INSERT INTO countries (iso, name) VALUES ('NF', 'Norfolk Island');
INSERT INTO countries (iso, name) VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO countries (iso, name) VALUES ('NO', 'Norway');
INSERT INTO countries (iso, name) VALUES ('OM', 'Oman');
INSERT INTO countries (iso, name) VALUES ('PK', 'Pakistan');
INSERT INTO countries (iso, name) VALUES ('PW', 'Palau');
INSERT INTO countries (iso, name) VALUES ('PS', 'Palestine');
INSERT INTO countries (iso, name) VALUES ('PA', 'Panama');
INSERT INTO countries (iso, name) VALUES ('PG', 'Papua New Guinea');
INSERT INTO countries (iso, name) VALUES ('PY', 'Paraguay');
INSERT INTO countries (iso, name) VALUES ('PE', 'Peru');
INSERT INTO countries (iso, name) VALUES ('PH', 'Philippines');
INSERT INTO countries (iso, name) VALUES ('PN', 'Pitcairn');
INSERT INTO countries (iso, name) VALUES ('PL', 'Poland');
INSERT INTO countries (iso, name) VALUES ('PT', 'Portugal');
INSERT INTO countries (iso, name) VALUES ('PR', 'Puerto Rico');
INSERT INTO countries (iso, name) VALUES ('QA', 'Qatar');
INSERT INTO countries (iso, name) VALUES ('RE', 'Reunion');
INSERT INTO countries (iso, name) VALUES ('RO', 'Romania');
INSERT INTO countries (iso, name) VALUES ('RU', 'Russian Federation');
INSERT INTO countries (iso, name) VALUES ('RW', 'Rwanda');
INSERT INTO countries (iso, name) VALUES ('KN', 'Saint Kitts and Nevis');
INSERT INTO countries (iso, name) VALUES ('LC', 'Saint Lucia');
INSERT INTO countries (iso, name) VALUES ('VC', 'Saint Vincent and the Grenadines');
INSERT INTO countries (iso, name) VALUES ('WS', 'Samoa');
INSERT INTO countries (iso, name) VALUES ('SM', 'San Marino');
INSERT INTO countries (iso, name) VALUES ('ST', 'Sao Tome and Principe');
INSERT INTO countries (iso, name) VALUES ('SA', 'Saudi Arabia');
INSERT INTO countries (iso, name) VALUES ('SN', 'Senegal');
INSERT INTO countries (iso, name) VALUES ('RS', 'Serbia');
INSERT INTO countries (iso, name) VALUES ('SC', 'Seychelles');
INSERT INTO countries (iso, name) VALUES ('SL', 'Sierra Leone');
INSERT INTO countries (iso, name) VALUES ('SG', 'Singapore');
INSERT INTO countries (iso, name) VALUES ('SK', 'Slovakia');
INSERT INTO countries (iso, name) VALUES ('SI', 'Slovenia');
INSERT INTO countries (iso, name) VALUES ('SB', 'Solomon Islands');
INSERT INTO countries (iso, name) VALUES ('SO', 'Somalia');
INSERT INTO countries (iso, name) VALUES ('ZA', 'South Africa');
INSERT INTO countries (iso, name) VALUES ('GS', 'South Georgia South Sandwich Islands');
INSERT INTO countries (iso, name) VALUES ('SS', 'South Sudan');
INSERT INTO countries (iso, name) VALUES ('ES', 'Spain');
INSERT INTO countries (iso, name) VALUES ('LK', 'Sri Lanka');
INSERT INTO countries (iso, name) VALUES ('SH', 'St. Helena');
INSERT INTO countries (iso, name) VALUES ('PM', 'St. Pierre and Miquelon');
INSERT INTO countries (iso, name) VALUES ('SD', 'Sudan');
INSERT INTO countries (iso, name) VALUES ('SR', 'Suriname');
INSERT INTO countries (iso, name) VALUES ('SJ', 'Svalbard and Jan Mayen Islands');
INSERT INTO countries (iso, name) VALUES ('SZ', 'Swaziland');
INSERT INTO countries (iso, name) VALUES ('SE', 'Sweden');
INSERT INTO countries (iso, name) VALUES ('CH', 'Switzerland');
INSERT INTO countries (iso, name) VALUES ('SY', 'Syrian Arab Republic');
INSERT INTO countries (iso, name) VALUES ('TW', 'Taiwan');
INSERT INTO countries (iso, name) VALUES ('TJ', 'Tajikistan');
INSERT INTO countries (iso, name) VALUES ('TZ', 'Tanzania, United Republic of');
INSERT INTO countries (iso, name) VALUES ('TH', 'Thailand');
INSERT INTO countries (iso, name) VALUES ('TG', 'Togo');
INSERT INTO countries (iso, name) VALUES ('TK', 'Tokelau');
INSERT INTO countries (iso, name) VALUES ('TO', 'Tonga');
INSERT INTO countries (iso, name) VALUES ('TT', 'Trinidad and Tobago');
INSERT INTO countries (iso, name) VALUES ('TN', 'Tunisia');
INSERT INTO countries (iso, name) VALUES ('TR', 'Turkey');
INSERT INTO countries (iso, name) VALUES ('TM', 'Turkmenistan');
INSERT INTO countries (iso, name) VALUES ('TC', 'Turks and Caicos Islands');
INSERT INTO countries (iso, name) VALUES ('TV', 'Tuvalu');
INSERT INTO countries (iso, name) VALUES ('UG', 'Uganda');
INSERT INTO countries (iso, name) VALUES ('UA', 'Ukraine');
INSERT INTO countries (iso, name) VALUES ('AE', 'United Arab Emirates');
INSERT INTO countries (iso, name) VALUES ('GB', 'United Kingdom');
INSERT INTO countries (iso, name) VALUES ('US', 'United States');
INSERT INTO countries (iso, name) VALUES ('UM', 'United States minor outlying islands');
INSERT INTO countries (iso, name) VALUES ('UY', 'Uruguay');
INSERT INTO countries (iso, name) VALUES ('UZ', 'Uzbekistan');
INSERT INTO countries (iso, name) VALUES ('VU', 'Vanuatu');
INSERT INTO countries (iso, name) VALUES ('VA', 'Vatican City State');
INSERT INTO countries (iso, name) VALUES ('VE', 'Venezuela');
INSERT INTO countries (iso, name) VALUES ('VN', 'Vietnam');
INSERT INTO countries (iso, name) VALUES ('VG', 'Virgin Islands (British)');
INSERT INTO countries (iso, name) VALUES ('VI', 'Virgin Islands (U.S.)');
INSERT INTO countries (iso, name) VALUES ('WF', 'Wallis and Futuna Islands');
INSERT INTO countries (iso, name) VALUES ('EH', 'Western Sahara');
INSERT INTO countries (iso, name) VALUES ('YE', 'Yemen');
INSERT INTO countries (iso, name) VALUES ('ZM', 'Zambia');
INSERT INTO countries (iso, name) VALUES ('ZW', 'Zimbabwe');

-- GENRES
INSERT INTO genres (name, create_at) VALUES ('Rock', '2017-07-23 13:10:11');
INSERT INTO genres (name, create_at) VALUES ('Pop', '2017-07-23 13:10:12');
INSERT INTO genres (name, create_at) VALUES ('Metal', '2017-07-23 13:10:13');
INSERT INTO genres (name, create_at) VALUES ('Hard Rock', '2017-07-23 13:10:14');
INSERT INTO genres (name, create_at) VALUES ('Jazz', '2017-07-23 13:10:15');
INSERT INTO genres (name, create_at) VALUES ('Blues', '2017-07-23 13:10:16');

-- MUSICIANS
INSERT INTO musicians (first_Name, last_Name, age, active, instrument, create_at, photo) VALUES ('James Alan', 'Hetfield', '57', 1, 'GUITAR', '2017-07-23 13:10:11', NULL);
INSERT INTO musicians (first_Name, last_Name, age, active, instrument, create_at, photo) VALUES ('Lars', 'Ulrich', '56', 1, 'DRUMS', '2017-07-23 13:10:12', NULL);
INSERT INTO musicians (first_Name, last_Name, age, active, instrument, create_at, photo) VALUES ('Kirk Lee', 'Hammett', '57', 1, 'GUITAR', '2017-07-23 13:10:13', NULL);
INSERT INTO musicians (first_Name, last_Name, age, active, instrument, create_at, photo) VALUES ('Robert', 'Trujillo', '56', 1, 'BASS', '2017-07-23 13:10:14', NULL);
INSERT INTO musicians (first_Name, last_Name, age, active, instrument, create_at, photo) VALUES ('Jason Curtis', 'Newsted', '57', 0, 'BASS', '2017-07-23 13:10:16', NULL);

INSERT INTO musicians (first_Name, last_Name, age, active, instrument, create_at, photo) VALUES ('Matthew James', 'Bellamy', '42', 1, 'GUITAR', '2017-07-23 13:10:17', NULL);
INSERT INTO musicians (first_Name, last_Name, age, active, instrument, create_at, photo) VALUES ('Christopher Anthony', 'Wolstenholme', '41', 1, 'BASS', '2017-07-23 13:10:18', NULL);
INSERT INTO musicians (first_Name, last_Name, age, active, instrument, create_at, photo) VALUES ('Dominic James', 'Howard', '42', 0, 'DRUMS', '2017-07-23 13:10:19', NULL);

-- BANDS
INSERT INTO bands (name, start, country_iso) VALUES('Metallica','1983-02-01', 'US');
INSERT INTO bands (name, start, country_iso) VALUES('Muse','1994-01-01', 'GB');

-- BANDS_GENRES
INSERT INTO bands_genres (band_id, genres_id) VALUES(1, 4);
INSERT INTO bands_genres (band_id, genres_id) VALUES(2, 1);

-- BANDS_MUSICIANS
INSERT INTO bands_musicians (band_id, musicians_id) VALUES(1, 1);
INSERT INTO bands_musicians (band_id, musicians_id) VALUES(1, 2);
INSERT INTO bands_musicians (band_id, musicians_id) VALUES(1, 3);
INSERT INTO bands_musicians (band_id, musicians_id) VALUES(1, 4);
INSERT INTO bands_musicians (band_id, musicians_id) VALUES(1, 5);
INSERT INTO bands_musicians (band_id, musicians_id) VALUES(2, 6);
INSERT INTO bands_musicians (band_id, musicians_id) VALUES(2, 7);
INSERT INTO bands_musicians (band_id, musicians_id) VALUES(2, 8);

-- RECORDS
INSERT INTO records (name, release, band_id) VALUES ('Kill Em All', '1983-07-25', 1);
INSERT INTO records (name, release, band_id) VALUES ('Ride the Lightning', '1984-07-27', 1);
INSERT INTO records (name, release, band_id) VALUES ('Master of Puppets', '1986-03-03', 1);
INSERT INTO records (name, release, band_id) VALUES ('...And Justice for All', '1988-08-25', 1);
INSERT INTO records (name, release, band_id) VALUES ('Metallica', '1991-08-12', 1);
INSERT INTO records (name, release, band_id) VALUES ('Load', '1996-06-04', 1);
INSERT INTO records (name, release, band_id) VALUES ('ReLoad', '1997-11-18', 1);
INSERT INTO records (name, release, band_id) VALUES ('St. Anger', '2003-06-06', 1);
INSERT INTO records (name, release, band_id) VALUES ('Death Magnetic', '2008-09-12', 1);
INSERT INTO records (name, release, band_id) VALUES ('Hardwired... to Self-Destruct', '2016-11-18', 1);

INSERT INTO records (name, release, band_id) VALUES ('Showbiz', '1999-09-07', 2);
INSERT INTO records (name, release, band_id) VALUES ('Origin of Symmetry', '2001-07-17', 2);
INSERT INTO records (name, release, band_id) VALUES ('Absolution', '2003-09-29', 2);
INSERT INTO records (name, release, band_id) VALUES ('Black Holes and Revelations', '2006-07-03', 2);
INSERT INTO records (name, release, band_id) VALUES ('The Resistance', '2009-09-14', 2);
INSERT INTO records (name, release, band_id) VALUES ('The 2nd Law', '2012-10-10', 2);
INSERT INTO records (name, release, band_id) VALUES ('Drones', '2015-06-08', 2);
INSERT INTO records (name, release, band_id) VALUES ('Simulation Theory', '2018-11-09', 2);

-- LABELS
INSERT INTO labels (name, create_at, email, country_iso) VALUES ('Warner Music Group', '2003-01-01', 'warner.music.group@warner.com', 'US');
INSERT INTO labels (name, create_at, email, country_iso) VALUES ('Sony Music', '2001-01-01', 'sony.music@warner.com', 'US');
INSERT INTO labels (name, create_at, email, country_iso) VALUES ('EMI', '2006-01-01', 'warner.music.group@warner.com', 'US');
INSERT INTO labels (name, create_at, email, country_iso) VALUES ('Columbia-CBS Recors', '1999-01-01', 'warner.music.group@warner.com', 'US');
INSERT INTO labels (name, create_at, email, country_iso) VALUES ('MCA', '1997-01-01', 'warner.music.group@warner.com', 'US');
INSERT INTO labels (name, create_at, email, country_iso) VALUES ('Polygram', '2005-01-01', 'warner.music.group@warner.com', 'US');
INSERT INTO labels (name, create_at, email, country_iso) VALUES ('Universal Music Group', '2002-01-01', 'warner.music.group@warner.com', 'US');

-- LABELS_RECORDS
INSERT INTO labels_records (label_id, records_id) VALUES (1, 1);
INSERT INTO labels_records (label_id, records_id) VALUES (1, 2);
INSERT INTO labels_records (label_id, records_id) VALUES (1, 3);
INSERT INTO labels_records (label_id, records_id) VALUES (2, 4);
INSERT INTO labels_records (label_id, records_id) VALUES (2, 5);
INSERT INTO labels_records (label_id, records_id) VALUES (3, 6);
INSERT INTO labels_records (label_id, records_id) VALUES (3, 7);
INSERT INTO labels_records (label_id, records_id) VALUES (3, 8);
INSERT INTO labels_records (label_id, records_id) VALUES (4, 9);
INSERT INTO labels_records (label_id, records_id) VALUES (4, 10);
INSERT INTO labels_records (label_id, records_id) VALUES (5, 11);
INSERT INTO labels_records (label_id, records_id) VALUES (5, 12);
INSERT INTO labels_records (label_id, records_id) VALUES (5, 13);
INSERT INTO labels_records (label_id, records_id) VALUES (5, 14);
INSERT INTO labels_records (label_id, records_id) VALUES (6, 15);
INSERT INTO labels_records (label_id, records_id) VALUES (6, 16);
INSERT INTO labels_records (label_id, records_id) VALUES (6, 17);
INSERT INTO labels_records (label_id, records_id) VALUES (6, 18);
