spring:
  profiles:
    active:
    - local
    
server:
  port: ${PORT:0}
  
eureka:
  instance:
    instance-id: microservice-util:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    
---

spring:
  profiles: local
  application:
    name: microservice-util
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

---

spring:
  profiles: test
  application:
    name: microservice-util
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

---

spring:
  profiles: dev
  application:
    name: microservice-util
  datasource:
    url: 
    driverClassName: 
    username:
    password:
  jpa:
    hibernate:
      ddl-auto:

---

spring:
  profiles: int
  application:
    name: microservice-util
  datasource:
    url: 
    driverClassName: 
    username: 
    password:
  jpa:
    hibernate:
      ddl-auto:

---


spring:
  profiles: prod
  application:
    name: microservice-util
  datasource:
    url: 
    driverClassName: 
    username: 
    password:
  jpa:
    hibernate:
      ddl-auto:
