spring:
  profiles:
    active:
    - local
     
---

spring:
  profiles: local
  application:
    name: microservice-bands
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: ${PORT:0}
  
eureka:
  instance:
    instance-id: microservice-bands:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  
---

spring:
  profiles: test
  application:
    name: microservice-bands
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

server:  port: ${PORT:0}
  
eureka:
  instance:
    instance-id: microservice-bands:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---

spring:
  profiles: dev
  application:
    name: microservice-bands
  datasource:
    url:
    driverClassName:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto:

server:
  port: ${PORT:0}
  
eureka:
  instance:
    instance-id: microservice-bands:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---

spring:
  profiles: int
  application:
    name: microservice-bands
  datasource:
    url: 
    driverClassName: 
    username: 
    password:
  jpa:
    hibernate:
      ddl-auto:

server:
  port: ${PORT:0}
  
eureka:
  instance:
    instance-id: microservice-bands:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---


spring:
  profiles: prod
  application:
    name: microservice-bands
  datasource:
    url: 
    driverClassName: 
    username: 
    password:
  jpa:
    hibernate:
      ddl-auto:

server:
  port: ${PORT:0}
  
eureka:
  instance:
    instance-id: microservice-bands:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka