spring:
  profiles:
    active:
    - local
  cloud:
    loadbalancer:
      ribbon.enabled: false
     
server:
  port: ${PORT:0}
  
eureka:
  instance:
    instance-id: microservice-bands:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---

spring:
  profiles: local
  application:
    name: microservice-bands
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  main:
    allow-bean-definition-overriding: true

okta:
  oauth2:
    issuer: https://dev-4272939.okta.com/oauth2/default
    audience: api://default
  
---

spring:
  profiles: test
  application:
    name: microservice-bands
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

---

spring:
  profiles: dev
  application:
    name: microservice-bands
  datasource:
    url:
    driverClassName:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto:

---

spring:
  profiles: int
  application:
    name: microservice-bands
  datasource:
    url: 
    driverClassName: 
    username: 
    password:
  jpa:
    hibernate:
      ddl-auto:

---


spring:
  profiles: prod
  application:
    name: microservice-bands
  datasource:
    url: 
    driverClassName: 
    username: 
    password:
  jpa:
    hibernate:
      ddl-auto:
